# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Sark Finance' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Sark Finance

  target 'Sark FinanceTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Sark FinanceUITests' do
    # Pods for testing
  end

end
